---
apiVersion: v1
kind: Namespace
metadata:
  name: dev-flow
---
apiVersion: v1
kind: Secret
metadata:
  name: dev-flow-secrets
  namespace: dev-flow
type: Opaque
stringData:
  ANTHROPIC_AUTH_TOKEN: "b02e2beeb5cd47f7870996a291c977a4.bxk5UMg9u4fNkosQ"
  ANTHROPIC_BASE_URL: "https://open.bigmodel.cn/api/anthropic"
  GITEA_SSH_KEY: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAABlwAAAAdzc2gtcn
    NhAAAAAwEAAQAAAYEA0abfN74N6gZICjR0Mkwhl/MD4C1qPyzroghnowsXOoYPTeyOVN4Q
    BQhN55Tu5tCsnzFjyGlVPzJp2RgGBC1bzn+k0Mo7GJoSH63Gef6yiwXzkJmFiAShA9Li67
    kJqtOJOmg1PlEspWvSWSyCZJ7upxKITQ6CcGWu6KRXhEBzB+nWjlS26AnEqgGKXAohQxGe
    lvIc2a4UEiLKaO6t2aZeHHsI8Fk0xgDZdQqeMrZkM/Qs82CQruP3SHMQ4kCErqm1FsLhCp
    vWmViX1fpdNHGwrJBBKkQVNWfs2GrYTbrMZpQFkh0gZWHV9aUpEtEa2B23MdwiMxnjWQtv
    VDOJqJKLkG2efrmSuE7tpnC2ir5ALnZtIu0PmGdfowulfG+4kgoTJkmLcI+zr6uzOadIN+
    STNZ8N32GEG7KpRmIvydN19aq1aaQiaRsl88ltem22ZJCSVF5qUnuS2uhyRj1cnX8t1qlp
    9LPmOyxrE6gvqLYc4rX1Ke3jfS+MQUAOVsnK9UMlAAAFiDy97788ve+/AAAAB3NzaC1yc2
    EAAAGBANGm3ze+DeoGSAo0dDJMIZfzA+Ataj8s66IIZ6MLFzqGD03sjlTeEAUITeeU7ubQ
    rJ8xY8hpVT8yadkYBgQtW85/pNDKOxiaEh+txnn+sosF85CZhYgEoQPS4uu5CarTiTpoNT
    5RLKVr0lksgmSe7qcSiE0OgnBlruikV4RAcwfp1o5UtugJxKoBilwKIUMRnpbyHNmuFBIi
    ymjurdmmXhx7CPBZNMYA2XUKnjK2ZDP0LPNgkK7j90hzEOJAhK6ptRbC4Qqb1plYl9X6XT
    RxsKyQQSpEFTVn7Nhq2E26zGaUBZIdIGVh1fWlKRLRGtgdtzHcIjMZ41kLb1QziaiSi5Bt
    nn65krhO7aZwtoq+QC52bSLtD5hnX6MLpXxvuJIKEyZJi3CPs6+rszmnSDfkkzWfDd9hhB
    uyqUZiL8nTdfWqtWmkImkbJfPJbXpttmSQklRealJ7ktrockY9XJ1/LdapafSz5jssaxOo
    L6i2HOK19Snt430vjEFADlbJyvVDJQAAAAMBAAEAAAGBAK0ek7Ju8QRvfWtX1x91eEQF+w
    xR1Csox8a8FAAxd1PvQZICJaH04NuW+OWjOQdGB1VJLnFecXNHCNqomMc4QVgqVQnIBLaS
    +yZHk95HMF3WY0LjUr13vRHwQUuPN2llVirxxA2acDiE6WSTeXTnPICfsAeZVKLFhII8ur
    vNkG9Xa8GKOKMw9cHAleTcxIyibweME8C4m4BCVEwD03EnjQ0Nl9sIfqiGKQsZ4npT3Dh+
    h+PMuIyCWD7uLWH3Dtk/7nanXyP5sXSzeiRmT3QCJ/yWRpqV30giIJMI74zA46GtNxydkx
    hEMa/Deqpd1M9YHjEdsFPM8Gg+2YbCJEp9F69VaquxsBteVi7l6f3NM+E1Sy2wvqN99tKf
    GWyqxNVGhuZMhZGGxRo7UKVaN3eJfBUEDV25vR0NcK64Ew1fqsLZuL+QMPS6LTSuPHFOYo
    6CmvDZGYETbDSFUuHBBgVXJU2Tz3lQUQ0J1AQ5gdpZdqajYRafGLDWjXM4L+omHvD2fQAA
    AMAHPjxKDZjUCpzcjR+iXA3xvlAeMi/LLM508RM7r/Sa4wbsbZmcfYKbWPmumY3firkMLu
    2nwUep28ci7vhQN4mOeQAgDSuLnZAZll1NegcgVS26Xp9PUy5rxR65tYAuZF2YFbTwuOYI
    IedWuoQF7ihByWZvaakAgG2Al0tMZ7RovAqkonaaCMs9KeetajaHRAhHkPwAvIzOun9VIv
    qaBkNUE4NMLmdC+G7oz/tC2ZAQTICn26spd3RaoQ66p8FVdI8AAADBAPknFkXi6s3OiGaf
    4f1qOTkUjqgB/D0SN/XZKsb6jZPwdJIXLnE3v1o+QD7Fvrrzmlfuw7yUCcSgHvrAjnZBls
    /3tBIQYhuJZ2RQqEh0HbdKIIm+Jyv9Mn2kKyAesrpZCMpVBlQAn5vuWxRtnUrDbFkprbLG
    POywJpau9I6bk59OkjGsjyge3KHCqibBSDtJVJ9kw2o74HzES/zGo62Qma3/NuBIcv9biC
    4Ly4Bno2D23Y2vJQlduMiUAcFU/hrvHwAAAMEA12ngfAeYuJbaLzXn5YBBR1seFLKgiVT1
    5m+pr8pmYs5dOcUSkj3rM0OgoKZkMVmPzRWiAeHB9aTN+pq3lduvtVCpv6faI4R8rsPlk/
    v4MSC6Ao4noGBYS31hQwCyW87I85bM01kko3gJ2Q9uEwyh+rMsSpBzYuaSzp1y06Bojs+y
    J19wrdfKfexcjeqK1U+xOmYFaYKEsfLmBKUf9zJ7Xh5tbgaTTgFZla6ab494uc6vaqF90e
    1HzMqX4r9hdfk7AAAAEHR5QHR5bWJwLTIubG9jYWwBAg==
    -----END OPENSSH PRIVATE KEY-----
